name = "trivia-clash-server"
main = "src/worker.ts"
compatibility_date = "2026-10-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "triviaclash-db-v3"
database_id = "bc0e5a84-b5d5-4ae2-bdac-2a198edfd9db"
migrations_dir = "src/db/migrations"

[triggers]
crons = ["* * * * *"]

# Configure VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY and VAPID_SUBJECT with Wrangler secrets.
