name = "trivia-clash-server"
main = "src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "triviaclash-db-v2"
database_id = "50b2d81d-1956-413e-8e59-fb69decf0aca"
migrations_dir = "src/db/migrations"
